[package]
name = "create_image_variation"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
openai_dive = { path = "./../../../openai_dive", features = ["download"] }
tokio = { version = "1.0", features = ["full"] }
