[package]
name = "create_chat_completion_simple"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
openai_dive = { path = "./../../../openai-client", features = ["simple"] }
tokio = { version = "1.0", features = ["full"] }
