[package]
name = "create_chat_completion_stream"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
openai_dive = { path = "./../../../../openai-client", features = ["stream"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
