[package]
name = "create_chat_completion"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
openai_dive = { path = "./../../../openai_dive", features = ["log"] }
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
ftail = "0.2"
